version: '3.8'

services:
  postgress:
    container_name: nest-clean-postgress
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-clean
      PGDATA: /data/postgress
    volumes:
      - ./data/pg:/data/postgress
